[github]
python-genpackagedoc=
python-extensions-collection=
python-jsonpreprocessor=
python-testresultdbaccess=
python-pytestlog2db=
python-microservice-base=
python-microservice-cleware-switch=
python-rabbitmq-messagebus=

robotframework-extensions-collection=
robotframework-qconnect-base=
robotframework-selftest=
robotframework-testsuitesmanagement=
robotframework-dbus=
robotframework-qconnect-winapp=
robotframework-tutorial=
robotframework-robotlog2rqm=
robotframework-robotlog2db=
robotframework-doip=mar3hc/support-libdoc-generate
robotframework-prometheus=
robotframework-uds=mar3hc/update-keywords-for-generate-libdoc
robotframework-documentation=

testresultwebapp=
vscode-jsonp=
vscode-welcome=mar3hc/feat/implement-new-webview

[supported-server]
github=https://github.com/test-fullautomation