[github]
python-genpackagedoc=mar3hc/feat/extend-setup-with-toml
python-extensions-collection=mar3hc/feat/extend-setup-with-toml
python-jsonpreprocessor=mar3hc/feat/extend-setup-with-toml
python-testresultdbaccess=mar3hc/feat/extend-setup-with-toml
python-pytestlog2db=mar3hc/feat/extend-setup-with-toml
python-microservice-base=mar3hc/feat/extend-setup-with-toml
python-microservice-cleware-switch=mar3hc/feat/extend-setup-with-toml
python-rabbitmq-messagebus=mar3hc/feat/extend-setup-with-toml

robotframework-extensions-collection=
robotframework-qconnect-base=
robotframework-selftest=
robotframework-testsuitesmanagement=
robotframework-dbus=
robotframework-qconnect-winapp=
robotframework-tutorial=
robotframework-robotlog2rqm=
robotframework-robotlog2db=
robotframework-doip=
robotframework-prometheus=
robotframework-uds=
robotframework-documentation=

testresultwebapp=
vscode-jsonp=
vscode-welcome=
robotframework-aio-website=

[supported-server]
github=https://github.com/test-fullautomation