[github]
python-genpackagedoc=mar3hc/feat/extend-setup-with-toml
python-extensions-collection=mar3hc/feat/extend-setup-with-toml
python-jsonpreprocessor=mar3hc/feat/extend-setup-with-toml
python-testresultdbaccess=mar3hc/feat/extend-setup-with-toml
python-pytestlog2db=mar3hc/feat/extend-setup-with-toml
python-microservice-base=mar3hc/feat/extend-setup-with-toml
python-microservice-cleware-switch=mar3hc/feat/extend-setup-with-toml
python-rabbitmq-messagebus=mar3hc/feat/extend-setup-with-toml

robotframework-extensions-collection=mar3hc/feat/extend-setup-with-toml
robotframework-qconnect-base=mar3hc/feat/extend-setup-with-toml
robotframework-selftest=
robotframework-testsuitesmanagement=mar3hc/feat/extend-setup-with-toml
robotframework-dbus=mar3hc/feat/extend-setup-with-toml
robotframework-qconnect-winapp=mar3hc/feat/extend-setup-with-toml
robotframework-tutorial=
robotframework-robotlog2rqm=mar3hc/feat/extend-setup-with-toml
robotframework-robotlog2db=mar3hc/feat/extend-setup-with-toml
robotframework-doip=mar3hc/feat/extend-setup-with-toml
robotframework-prometheus=mar3hc/feat/extend-setup-with-toml
robotframework-uds=mar3hc/feat/extend-setup-with-toml
robotframework=develop_6.1
robotframework-documentation=mar3hc/feat/extend-setup-with-toml

testresultwebapp=
vscode-jsonp=
vscode-welcome=
robotframework-aio-website=

[supported-server]
github=https://github.com/test-fullautomation