[github]
python-genpackagedoc=HolQue/task/setup_process
python-extensions-collection=HolQue/task/setup_process
python-jsonpreprocessor=HolQue/task/setup_process
python-testresultdbaccess=
python-pytestlog2db=
python-microservice-base=
python-microservice-cleware-switch=
python-rabbitmq-messagebus=HolQue/task/setup_process

robotframework-extensions-collection=HolQue/task/setup_process
robotframework-qconnect-base=HolQue/task/setup_process
robotframework-selftest=
robotframework-testsuitesmanagement=HolQue/task/setup_process_fix
robotframework-dbus=HolQue/task/setup_process
robotframework-qconnect-winapp=ntd1hc/feat/missing-component
robotframework-tutorial=
robotframework-robotlog2rqm=HolQue/task/setup_process
robotframework-robotlog2db=HolQue/task/setup_process
robotframework-doip=
robotframework-prometheus=HolQue/task/setup_process
robotframework-uds=
robotframework=develop_6.1
robotframework-documentation=

testresultwebapp=
vscode-jsonp=
vscode-welcome=
robotframework-aio-website=

[supported-server]
github=https://github.com/test-fullautomation