#!/bin/bash
#This script helps to clone all repositories

#
# import common bash scripts
#
. ./include/bash/common.sh



function parse_github_repo () {
	github_repo=($(git config -f $1 --list --name-only | grep github.))
	for repo in "${github_repo[@]}"
	do
	    reponame=${repo#github.}
		repo_url=$(git config -f $1 --get ${repo});
		if [[ "$repo_url" ==  "" ]]; then
			repo_url="https://github.com/test-fullautomation/${reponame}"
		fi
		echo -e "$COL_BLUE$BG_WHITE---- $repo$COL_RESET$COL_BLUE$BG_WHITE -----------------------------------------$COL_RESET"
		rm -rf "../$reponame"
		git clone "$repo_url" "../$reponame"
		if [ "$?" -ne 0 ]; then
			exit 1
		fi
	done
}

function parse_config () {
	echo "git config -f $1 --list --name-only | sed "s/.[^.]*$//" | uniq"
	conf_section=($(git config -f $1 --list --name-only | sed "s/.[^.]*$//" | uniq))
	#echo $conf_section
	for section in "${conf_section[@]}"
	do 
		if [[ "$section" == "internal" ]]; then
			parse_internal_repo $1
			if [ "$?" -ne 0 ]; then
				exit 1
			fi
		elif [[ "$section" == "github" ]]; then
			echo github parsing
			parse_github_repo $1
			if [ "$?" -ne 0 ]; then
				exit 1
			fi
		elif [[ "$section" == "gitlab" ]]; then
			echo gitlab parsing
			parse_gitlab_repo $1
			if [ "$?" -ne 0 ]; then
				exit 1
			fi
		elif [[ "$section" == "proxy" ]]; then
		    echo "TODO: Implement proxy config"
		else
			sec_name=$(git config -f "$1" --get ${section}.name);
			if [ "$sec_name" == "" ]; then
				sec_name=${section}
			fi
			
			echo -e "$COL_BLUE$BG_WHITE---- $sec_name$COL_RESET$COL_BLUE$BG_WHITE -----------------------------------------$COL_RESET"
			
			sec_path=$(git config -f $1 --get ${section}.path);
			if [ "$sec_path" == "" ]; then
				sec_path="../${sec_name}"
			fi
			sec_url=$(git config -f $1 --get ${section}.url);
			if [ "$sec_url" == "" ]; then
				sec_url="https://${BIOS_BOT_USERNAME}:${BIOS_BOT_PASSWORD_PREFIX}${BIOS_BOT_PASSWORD_SUFFIX}@sourcecode.socialcoding.bosch.com/scm/robfw/${sec_name}.git"
			fi
			rm -rf "$sec_path"
			git clone "$sec_url" "$sec_path"
			if [ "$?" -ne 0 ]; then
				exit 1
			fi
			echo
			echo
		fi
	done
}

function myini() {
	git config -f ./config/repositories/repositories_linux.conf --get $1;
}

echo -e "${COL_GREEN}####################################################################################${COL_RESET}"
echo -e "${COL_GREEN}#                                                                                  #${COL_RESET}"
echo -e "${COL_GREEN}#          Cloning BIOS repositories                                               #${COL_RESET}"
echo -e "${COL_GREEN}#                                                                                  #${COL_RESET}"
echo -e "${COL_GREEN}####################################################################################${COL_RESET}"
                                 

using_proxy=$(myini Proxy.enable)

if [ "$using_proxy" != "yes" ]; then
	echo " WARNING: ./repositories_linux.conf proxy.enable not enabled"
else
	proxy_url = $(myini Proxy.proxy)
	git config --global http.proxy $proxy_url
	goodmsg "Proxy enabled"
fi

#iterate over all repositories and apply now the clone command                    
parse_config ./config/repositories/repositories_linux.conf

./wget/install_linux_ntlm.sh
