texlive_packages=(
"multirow"
"booktabs"
"framed"
"fvextra"
"courier"
"efbox"
"grffile"
"pdfpages"
"tcolorbox"
"wasysym"
"wasy"
"fancyvrb"
"xcolor"
"etoolbox"
"upquote"
"lineno"
"eso-pic"
"lstaddons"
"pdflscape"
"infwarerr"
"pgf"
"environ"
"trimspaces"
"listings"
"pdfcol"
)
extra_packages=""
for package in ${texlive_packages[@]}; do
  extra_packages+="$package,"
done

choco install texlive --version=2022.20221202 --params "'/extraPackages:${extra_packages::-1}'"