"""
inno_setup_install.bzl - Custom repository_rule for the Inno Setup Compiler
=============================================================================

The official Inno Setup download ("isetup-5.5.1-unicode.exe") is a
self-extracting installer, not a plain zip/tar archive. Bazel's builtin
http_archive (used by the "python" module for CPython) cannot extract it
directly - it only understands standard archive formats (zip, tar, ...).

This repository_rule instead:
  1. Downloads the installer .exe with checksum verification (repo_ctx.download,
     same integrity guarantee as http_archive/http_file).
  2. Runs it in silent, PORTABLE mode ("/PORTABLE=1 /DIR=<repo_root>"), which
     makes Inno Setup's own installer place all its files (including
     ISCC.exe) directly into the Bazel-managed external repository
     directory - no registry entries, start menu shortcuts, file
     associations, or admin-rights/UAC elevation prompt. The /PORTABLE=1
     switch is essential here: without it, the installer's manifest requests
     administrator privileges unconditionally (it defaults to installing
     into "Program Files"), which triggers a Windows UAC confirmation
     dialog that none of the /VERYSILENT-style switches can suppress.
  3. Generates a BUILD.bazel file exposing the result as filegroups, exactly
     like the build_file_content used in a regular http_archive call.
"""

def _inno_setup_install_impl(repo_ctx):
    installer_name = "isetup-installer.exe"

    # Download with checksum verification - identical guarantee to
    # http_archive/http_file's sha256 attribute.
    repo_ctx.download(
        url = repo_ctx.attr.url,
        sha256 = repo_ctx.attr.sha256,
        output = installer_name,
    )

    # Run the installer silently, pointed at the repository directory itself.
    # Flags:
    #   /VERYSILENT       - no UI at all
    #   /SUPPRESSMSGBOXES - suppress any message boxes (e.g. "already installed")
    #   /NORESTART        - never trigger a reboot
    #   /SP-              - skip the "This will install..." confirmation
    #   /NOICONS          - don't create start menu icons
    #   /PORTABLE=1       - perform a PORTABLE installation (supported by the
    #                       official isetup-*.exe installer since Inno Setup
    #                       5.3.9, so 5.5.1 supports it): no registry entries,
    #                       no file associations, no elevation/admin rights
    #                       requested at all. Without this switch, the
    #                       installer's own manifest requests administrator
    #                       privileges (it's designed to install into
    #                       "Program Files" by default), which triggers the
    #                       Windows UAC "Do you want to allow this app to
    #                       make changes..." prompt regardless of any
    #                       /VERYSILENT-style flag - UAC elevation cannot be
    #                       suppressed via Inno Setup's own silent switches,
    #                       since it happens before the installer code (and
    #                       therefore before /VERYSILENT) even runs.
    #   /DIR=...          - install target directory (repo root)
    result = repo_ctx.execute(
        [
            repo_ctx.path(installer_name),
            "/VERYSILENT",
            "/SUPPRESSMSGBOXES",
            "/NORESTART",
            "/SP-",
            "/NOICONS",
            "/PORTABLE=1",
            "/DIR=" + str(repo_ctx.path("")),
        ],
        timeout = 600,
    )

    if result.return_code != 0:
        fail(
            "Silent Inno Setup installation failed (exit code %d).\nstdout:\n%s\nstderr:\n%s" %
            (result.return_code, result.stdout, result.stderr),
        )

    # Sanity check: ISCC.exe must now exist in the repo directory.
    if not repo_ctx.path("ISCC.exe").exists:
        fail(
            "ISCC.exe not found in %s after silent install. " % repo_ctx.path("") +
            "The installer layout may have changed - inspect the extracted " +
            "directory contents and adjust inno_setup_install.bzl accordingly.",
        )

    repo_ctx.file(
        "BUILD.bazel",
        content = """
# Build file for the Inno Setup installation, generated by inno_setup_install.bzl.
# Exposes the compiler executable (and the rest of the installed files, in
# case ISCC.exe needs sibling files/DLLs at runtime) as filegroups.

# Complete Inno Setup installation (compiler + all support files/DLLs).
# Used by: components/inno_setup:iscc (via runfiles, if ever needed).
filegroup(
    name = "runtime",
    srcs = glob(["**"], exclude = ["**/__pycache__/**", "{installer}"]),
    visibility = ["//visibility:public"],
)

# The compiler executable only.
# Used for: Invoking "ISCC.exe" during the build process.
filegroup(
    name = "iscc",
    srcs = ["ISCC.exe"],
    visibility = ["//visibility:public"],
)
""".format(installer = installer_name),
    )

inno_setup_install = repository_rule(
    implementation = _inno_setup_install_impl,
    attrs = {
        "url": attr.string(
            mandatory = True,
            doc = "Download URL of the Inno Setup installer .exe.",
        ),
        "sha256": attr.string(
            mandatory = True,
            doc = "Expected SHA-256 checksum of the downloaded installer .exe.",
        ),
    },
    doc = """Downloads the Inno Setup installer and silently installs it into
    the repository directory, exposing ISCC.exe as a Bazel target.

    Unlike http_archive, this does not attempt to "extract" the downloaded
    file as a zip/tar archive - it runs it as what it actually is: a Windows
    installer executable, using its documented unattended command-line
    switches to place files directly into the repository directory.
    """,
)
