load(":pip_install.bzl", "pip_install_dir")

pip_install_dir(
    name = "site_packages",
    requirements = "requirements_lock.txt",
    interpreter = "@python_portable_windows//:interpreter",
    runtime = "@python_portable_windows//:runtime",
    env = {
        "HTTPS_PROXY": "http://rb-proxy-de.bosch.com:8080",
        "HTTP_PROXY": "http://rb-proxy-de.bosch.com:8080",
        "NO_PROXY": "localhost,127.0.0.1,.bosch.com",
    },
    visibility = ["//components/installer:__pkg__"],
)















# # # ---------------------------------------------------------------
# # # previous

# # # # components/py_modules/BUILD.bazel
# # # load("@aspect_bazel_lib//lib:run_binary.bzl", "run_binary")   # <- nicht skylib!
# # # load("@bazel_skylib//rules:native_binary.bzl", "native_binary")

# # # # Der portable Interpreter als aufrufbares Tool
# # # native_binary(
    # # # name = "portable_python",
    # # # src = "@python_portable_windows//:interpreter",
    # # # out = "python.exe",
    # # # data = ["@python_portable_windows//:runtime"],   # Lib/, DLLs/ müssen mit!
# # # )

# # # run_binary(
    # # # name = "site_packages",
    # # # tool = ":portable_python",
    # # # srcs = ["requirements_lock.txt"],
    # # # out_dirs = ["site-packages"],
    # # # args = [
        # # # "-m", "pip", "install",
        # # # "--requirement", "$(location requirements_lock.txt)",   # src -> OK
        # # # "--require-hashes",
        # # # "--target", "$(RULEDIR)/site-packages",                 # output -> so
        # # # "--no-compile",
        # # # "--disable-pip-version-check",
    # # # ],
    # # # tags = ["requires-network", "no-sandbox"],
    # # # visibility = ["//installer:__pkg__"],
# # # )


# # # ---------------------------------------------------------------
# # # previous

# # # # components/py_modules/BUILD.bazel
# # # load("@bazel_skylib//rules:native_binary.bzl", "native_binary")
# # # load("@bazel_skylib//rules:run_binary.bzl", "run_binary")

# # # # Der portable Interpreter als aufrufbares Tool
# # # native_binary(
    # # # name = "portable_python",
    # # # src = "@python_portable_windows//:interpreter",
    # # # out = "python.exe",
    # # # data = ["@python_portable_windows//:runtime"],   # Lib/, DLLs/ müssen mit!
# # # )

# # # run_binary(
    # # # name = "site_packages",
    # # # tool = ":portable_python",
    # # # srcs = ["requirements_lock.txt"],
    # # # out_dirs = ["site-packages"],
    # # # args = [
        # # # "-m", "pip", "install",
        # # # "--requirement", "$(location requirements_lock.txt)",
        # # # "--require-hashes",
        # # # "--target", "$(location site-packages)",
        # # # "--no-compile",              # keine .pyc   die sind pfadabhängig
        # # # # ? "--disable-pip-version-check",
    # # # ],
    # # # tags = ["requires-network", "no-sandbox"],
    # # # visibility = ["//installer:__pkg__"],
# # # )



# # # ---------------------------------------------------------------
# # # previous

# # # load("@bazel_skylib//rules:run_binary.bzl", "run_binary")

# # # run_binary(
    # # # name = "site_packages",
    # # # tool = "//components/py_modules:pip_install",   # kleines py_binary-Wrapper-Skript
    # # # srcs = ["requirements.txt"],
    # # # out_dirs = ["site-packages"],
    # # # args = [
        # # # "--requirements=\$(location requirements.txt)",
        # # # "--target=\$(location site-packages)",
    # # # ],
    # # # visibility = ["//installer:__pkg__"],
# # # )
