#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Python Installation Builder with Bazel

Creates a portable Python installation package with all dependencies
for distribution and installation on target systems.

Usage:
    1. Configure requirements.txt with desired packages
    2. Run: bazel build //tools/python_installer:installer_package
    3. Extract and run install.bat on target system
"""

import os
import sys
import shutil
import subprocess
import zipfile
from pathlib import Path
import argparse


def get_bazel_info(key):
    """Get information from Bazel."""
    try:
        result = subprocess.run(
            ['bazel', 'info', key],
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Error getting Bazel info for '{key}': {e}")
        sys.exit(1)


def run_command(cmd, description):
    """Run a command with error handling."""
    print(f"\n{'='*70}")
    print(f"🔧 {description}")
    print(f"{'='*70}")
    print(f"Command: {' '.join(cmd)}")
    
    result = subprocess.run(cmd)
    if result.returncode != 0:
        print(f"❌ Error: {description} failed")
        sys.exit(1)
    
    print(f"✅ {description} completed successfully")


def create_installer_structure(output_dir):
    """Create the installer directory structure."""
    print(f"\n📁 Creating installer structure in: {output_dir}")
    
    dirs = [
        output_dir / "python",
        output_dir / "wheels", 
        output_dir / "scripts",
        output_dir / "config",
    ]
    
    for directory in dirs:
        directory.mkdir(parents=True, exist_ok=True)
        print(f"  ✓ Created: {directory}")


def copy_python_runtime(output_dir):
    """Copy Python runtime from Bazel toolchain."""
    print("\n🐍 Copying Python runtime...")
    
    # Get Python executable from Bazel
    result = subprocess.run(
        ['bazel', 'run', '@python3//:python', '--', '-c', 
         'import sys; print(sys.executable)'],
        capture_output=True,
        text=True
    )
    
    python_exe = result.stdout.strip()
    if not python_exe:
        print("❌ Could not determine Python executable path")
        sys.exit(1)
    
    python_root = Path(python_exe).parent.parent  # Go up from bin/python.exe
    
    print(f"  Source: {python_root}")
    print(f"  Target: {output_dir / 'python'}")
    
    # Copy Python installation
    if python_root.exists():
        shutil.copytree(
            python_root, 
            output_dir / "python",
            dirs_exist_ok=True,
            ignore=shutil.ignore_patterns('__pycache__', '*.pyc', '*.pyo')
        )
        print("  ✓ Python runtime copied")
    else:
        print(f"❌ Python directory not found: {python_root}")
        sys.exit(1)


def copy_wheels(output_dir):
    """Copy all PyPI wheels from Bazel external repository."""
    print("\n📦 Copying Python packages (wheels)...")
    
    output_base = get_bazel_info('output_base')
    pypi_repo = Path(output_base) / "external" / "pypi"
    
    if not pypi_repo.exists():
        print(f"❌ PyPI repository not found: {pypi_repo}")
        print("   Run 'bazel build' first to download dependencies")
        sys.exit(1)
    
    wheels_target = output_dir / "wheels"
    
    # Find all .whl files
    wheel_count = 0
    for wheel_file in pypi_repo.rglob("*.whl"):
        target = wheels_target / wheel_file.name
        if not target.exists():
            shutil.copy2(wheel_file, target)
            print(f"  ✓ {wheel_file.name}")
            wheel_count += 1
    
    print(f"  ✓ Copied {wheel_count} wheel files")


def create_install_script_windows(output_dir, requirements_file):
    """Create Windows installation script."""
    print("\n📝 Creating Windows installation script...")
    
    script_content = f"""@echo off
REM ============================================
REM Python Installation Script (Windows)
REM Generated by Bazel Python Installer
REM ============================================

setlocal enabledelayedexpansion

REM Get installation directory
set SCRIPT_DIR=%~dp0
set INSTALL_ROOT=%SCRIPT_DIR%..

REM Paths
set PYTHON_DIR=%INSTALL_ROOT%\\python
set WHEELS_DIR=%INSTALL_ROOT%\\wheels
set SCRIPTS_DIR=%INSTALL_ROOT%\\scripts
set PYTHON_EXE=%PYTHON_DIR%\\bin\\python.exe

REM Alternative Python path for different structures
if not exist "%PYTHON_EXE%" set PYTHON_EXE=%PYTHON_DIR%\\python.exe

echo ============================================
echo Python Installation
echo ============================================
echo.
echo Installation directory: %INSTALL_ROOT%
echo Python executable: %PYTHON_EXE%
echo.

REM Check if Python exists
if not exist "%PYTHON_EXE%" (
    echo ERROR: Python executable not found!
    echo Expected: %PYTHON_EXE%
    pause
    exit /b 1
)

REM Display Python version
echo Checking Python version...
"%PYTHON_EXE%" --version
if errorlevel 1 (
    echo ERROR: Python is not working correctly!
    pause
    exit /b 1
)
echo.

REM Upgrade pip
echo ============================================
echo Upgrading pip...
echo ============================================
"%PYTHON_EXE%" -m pip install --upgrade --no-index --find-links "%WHEELS_DIR%" pip
echo.

REM Install all wheels from wheels directory
echo ============================================
echo Installing Python packages...
echo ============================================

set PACKAGE_COUNT=0
for %%w in ("%WHEELS_DIR%\\*.whl") do (
    echo Installing: %%~nxw
    "%PYTHON_EXE%" -m pip install --no-index --find-links "%WHEELS_DIR%" "%%w"
    if errorlevel 1 (
        echo WARNING: Failed to install %%~nxw
    ) else (
        set /a PACKAGE_COUNT+=1
    )
)

echo.
echo ============================================
echo Installation Summary
echo ============================================
echo Installed packages: %PACKAGE_COUNT%
echo Python: %PYTHON_EXE%
echo Wheels: %WHEELS_DIR%
echo.

REM Create activation script
echo Creating activation script...
set ACTIVATE_SCRIPT=%INSTALL_ROOT%\\activate.bat

(
echo @echo off
echo REM Activate Python environment
echo set PYTHON_ROOT=%PYTHON_DIR%
echo set PYTHON_EXE=%PYTHON_EXE%
echo set PATH=%PYTHON_DIR%\\bin;%PYTHON_DIR%\\Scripts;%%PATH%%
echo echo Python environment activated
echo echo Python: %%PYTHON_EXE%%
) > "%ACTIVATE_SCRIPT%"

echo Activation script: %ACTIVATE_SCRIPT%
echo.

REM Test installation
echo ============================================
echo Testing Installation
echo ============================================
"%PYTHON_EXE%" -c "import sys; print(f'Python {{sys.version}}'); print(f'Executable: {{sys.executable}}')"

echo.
echo ============================================
echo Installation Complete!
echo ============================================
echo.
echo To use this Python installation:
echo   1. Run: %ACTIVATE_SCRIPT%
echo   2. Or use directly: %PYTHON_EXE%
echo.
echo Installed packages can be verified with:
echo   %PYTHON_EXE% -m pip list
echo.

pause
"""
    
    script_path = output_dir / "scripts" / "install.bat"
    with open(script_path, 'w', newline='\r\n') as f:
        f.write(script_content)
    
    print(f"  ✓ Created: {script_path}")


def create_install_script_linux(output_dir, requirements_file):
    """Create Linux/macOS installation script."""
    print("\n📝 Creating Linux installation script...")
    
    script_content = f"""#!/bin/bash
# ============================================
# Python Installation Script (Linux/macOS)
# Generated by Bazel Python Installer
# ============================================

set -e

# Get installation directory
SCRIPT_DIR="$( cd "$( dirname "${{BASH_SOURCE[0]}}" )" &> /dev/null && pwd )"
INSTALL_ROOT="$(dirname "$SCRIPT_DIR")"

# Paths
PYTHON_DIR="$INSTALL_ROOT/python"
WHEELS_DIR="$INSTALL_ROOT/wheels"
PYTHON_EXE="$PYTHON_DIR/bin/python"

echo "============================================"
echo "Python Installation"
echo "============================================"
echo ""
echo "Installation directory: $INSTALL_ROOT"
echo "Python executable: $PYTHON_EXE"
echo ""

# Check if Python exists
if [ ! -f "$PYTHON_EXE" ]; then
    echo "ERROR: Python executable not found!"
    echo "Expected: $PYTHON_EXE"
    exit 1
fi

# Make Python executable
chmod +x "$PYTHON_EXE"

# Display Python version
echo "Checking Python version..."
"$PYTHON_EXE" --version
echo ""

# Upgrade pip
echo "============================================"
echo "Upgrading pip..."
echo "============================================"
"$PYTHON_EXE" -m pip install --upgrade --no-index --find-links "$WHEELS_DIR" pip
echo ""

# Install all wheels
echo "============================================"
echo "Installing Python packages..."
echo "============================================"

PACKAGE_COUNT=0
for wheel in "$WHEELS_DIR"/*.whl; do
    if [ -f "$wheel" ]; then
        echo "Installing: $(basename "$wheel")"
        if "$PYTHON_EXE" -m pip install --no-index --find-links "$WHEELS_DIR" "$wheel"; then
            ((PACKAGE_COUNT++))
        else
            echo "WARNING: Failed to install $(basename "$wheel")"
        fi
    fi
done

echo ""
echo "============================================"
echo "Installation Summary"
echo "============================================"
echo "Installed packages: $PACKAGE_COUNT"
echo "Python: $PYTHON_EXE"
echo "Wheels: $WHEELS_DIR"
echo ""

# Create activation script
echo "Creating activation script..."
ACTIVATE_SCRIPT="$INSTALL_ROOT/activate.sh"

cat > "$ACTIVATE_SCRIPT" << 'ACTIVATE_EOF'
#!/bin/bash
# Activate Python environment
SCRIPT_DIR="$( cd "$( dirname "${{BASH_SOURCE[0]}}" )" &> /dev/null && pwd )"
export PYTHON_ROOT="$SCRIPT_DIR/python"
export PATH="$PYTHON_ROOT/bin:$PATH"
echo "Python environment activated"
echo "Python: $(which python)"
ACTIVATE_EOF

chmod +x "$ACTIVATE_SCRIPT"
echo "Activation script: $ACTIVATE_SCRIPT"
echo ""

# Test installation
echo "============================================"
echo "Testing Installation"
echo "============================================"
"$PYTHON_EXE" -c "import sys; print(f'Python {{sys.version}}'); print(f'Executable: {{sys.executable}}')"

echo ""
echo "============================================"
echo "Installation Complete!"
echo "============================================"
echo ""
echo "To use this Python installation:"
echo "  1. Run: source $ACTIVATE_SCRIPT"
echo "  2. Or use directly: $PYTHON_EXE"
echo ""
echo "Installed packages can be verified with:"
echo "  $PYTHON_EXE -m pip list"
echo ""
"""
    
    script_path = output_dir / "scripts" / "install.sh"
    with open(script_path, 'w', newline='\n') as f:
        f.write(script_content)
    
    # Make executable
    script_path.chmod(0o755)
    
    print(f"  ✓ Created: {script_path}")


def create_readme(output_dir):
    """Create README for the installer package."""
    print("\n📄 Creating README...")
    
    readme_content = """# Python Installation Package

This package contains a complete Python installation with all required dependencies.

## Contents

- `python/` - Python runtime
- `wheels/` - Python packages (wheel files)
- `scripts/` - Installation scripts
- `README.md` - This file

## Installation

### Windows

1. Extract this archive to desired location
2. Run: `scripts\\install.bat`
3. Activate: `activate.bat`

### Linux/macOS

1. Extract this archive to desired location
2. Run: `bash scripts/install.sh`
3. Activate: `source activate.sh`

## Usage

After installation, you can use Python in two ways:

### Option 1: Direct execution

```bash
# Windows
python\\bin\\python.exe --version

# Linux/macOS
python/bin/python --version
```

### Option 2: Activate environment

```bash
# Windows
activate.bat
python --version

# Linux/macOS
source activate.sh
python --version
```

## Verification

List installed packages:

```bash
# Windows
python\\bin\\python.exe -m pip list

# Linux/macOS
python/bin/python -m pip list
```

## Package Contents

This installation includes the following Python packages:

- pytest
- colorama
- pyyaml
- jsonschema
- regex
- (and their dependencies)

See `wheels/` directory for complete list of included packages.

## Requirements

- No additional requirements
- Completely self-contained installation
- No internet connection needed for installation

## Generated by

Bazel Python Installer
Generated on: {generation_date}
"""
    
    from datetime import datetime
    readme_content = readme_content.format(
        generation_date=datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    )
    
    readme_path = output_dir / "README.md"
    with open(readme_path, 'w') as f:
        f.write(readme_content)
    
    print(f"  ✓ Created: {readme_path}")


def create_requirements_file(output_dir, source_requirements):
    """Copy requirements.txt to package."""
    if source_requirements and Path(source_requirements).exists():
        print(f"\n📋 Copying requirements.txt...")
        target = output_dir / "config" / "requirements.txt"
        shutil.copy2(source_requirements, target)
        print(f"  ✓ Copied: {target}")
        return target
    return None


def create_zip_package(output_dir, zip_name):
    """Create ZIP archive of the installation package."""
    print(f"\n📦 Creating ZIP package...")
    
    zip_path = output_dir.parent / f"{zip_name}.zip"
    
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(output_dir):
            for file in files:
                file_path = Path(root) / file
                arcname = file_path.relative_to(output_dir.parent)
                zipf.write(file_path, arcname)
                print(f"  ✓ Added: {arcname}")
    
    print(f"\n✅ ZIP package created: {zip_path}")
    print(f"   Size: {zip_path.stat().st_size / (1024*1024):.2f} MB")
    
    return zip_path


def main():
    parser = argparse.ArgumentParser(
        description='Build Python installation package with Bazel'
    )
    parser.add_argument(
        '-o', '--output',
        default='python_installer_output',
        help='Output directory name (default: python_installer_output)'
    )
    parser.add_argument(
        '-r', '--requirements',
        default='requirements.txt',
        help='Path to requirements.txt (default: requirements.txt)'
    )
    parser.add_argument(
        '--skip-build',
        action='store_true',
        help='Skip Bazel build step (use existing artifacts)'
    )
    parser.add_argument(
        '--no-zip',
        action='store_true',
        help='Do not create ZIP archive'
    )
    
    args = parser.parse_args()
    
    print("=" * 70)
    print("🚀 Python Installation Package Builder")
    print("=" * 70)
    
    # Step 1: Run Bazel build (unless skipped)
    if not args.skip_build:
        run_command(
            ['bazel', 'build', '//:python_with_deps'],
            "Building Python with dependencies"
        )
    else:
        print("\n⏭️  Skipping Bazel build (--skip-build)")
    
    # Step 2: Create output directory
    output_dir = Path.cwd() / args.output
    if output_dir.exists():
        print(f"\n🗑️  Removing existing output directory: {output_dir}")
        shutil.rmtree(output_dir)
    
    create_installer_structure(output_dir)
    
    # Step 3: Copy Python runtime
    copy_python_runtime(output_dir)
    
    # Step 4: Copy wheels
    copy_wheels(output_dir)
    
    # Step 5: Create installation scripts
    create_install_script_windows(output_dir, args.requirements)
    create_install_script_linux(output_dir, args.requirements)
    
    # Step 6: Create README
    create_readme(output_dir)
    
    # Step 7: Copy requirements.txt
    create_requirements_file(output_dir, args.requirements)
    
    # Step 8: Create ZIP package (optional)
    zip_path = None
    if not args.no_zip:
        zip_path = create_zip_package(output_dir, args.output)
    
    # Final summary
    print("\n" + "=" * 70)
    print("✅ Python Installation Package Build Complete!")
    print("=" * 70)
    print(f"\n📂 Output directory: {output_dir}")
    if zip_path:
        print(f"📦 ZIP package: {zip_path}")
    print("\n📋 Next steps:")
    print(f"   1. Distribute: {zip_path if zip_path else output_dir}")
    print(f"   2. Extract on target system")
    print(f"   3. Run installation script:")
    print(f"      - Windows: scripts\\install.bat")
    print(f"      - Linux:   bash scripts/install.sh")
    print()


if __name__ == '__main__':
    main()
